import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main
          className={cn(
            "relative h-full min-h-screen flex flex-col font-sans antialiased",
            inter.className
          )}
        >
          <Navbar />
          <div className="flex-1 flex-grow"> {children}</div>
        </main>
      </body>
    </html>
  );
}
